# Generated by Django 2.2 on 2019-04-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='checksum',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
