# Generated by Django 2.2 on 2019-04-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dapp', '0003_auto_20190412_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'get_latest_by': ['created']},
        ),
        migrations.AlterModelOptions(
            name='release',
            options={'get_latest_by': ['created']},
        ),
    ]
