# Generated by Django 2.2 on 2019-04-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dapp', '0004_auto_20190412_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
