# Generated by Django 2.2 on 2019-04-12 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dapp', '0005_application_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='default',
            new_name='is_default',
        ),
    ]
