# Generated by Django 2.2 on 2019-04-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dapp', '0006_auto_20190412_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'get_latest_by': ['created'], 'ordering': ['version']},
        ),
        migrations.AlterField(
            model_name='release',
            name='minimum',
            field=models.BooleanField(default=False, help_text='Minimum version that can access webservice.'),
        ),
    ]
